In [80]:
import pandas as pd

In [81]:
inventory_data = pd.read_csv("dataset/cleaned_inventory_data.csv")

In [82]:
inventory_data.head(10)

,Brand/Company Name,Strategy,App/URL,Exchange,Impressions,Clicks,Total Conversions,Gross Cost,Net Cost,Viewable Impressions,Measurable Impressions,CPC,CTR,CPA,CPM,CVR
0,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,BidSwitch,4.0,0.0,0.0,0.008026,0.002576,1.0,4.0,0.0,0.0,0.0,0.644087,0.0
1,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,Google Ad Manager,1.0,0.0,0.0,0.000592,0.000190,0.0,0.0,0.0,0.0,0.0,0.190032,0.0
2,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,Magnite DV+,7.0,0.0,0.0,0.012468,0.004002,2.0,6.0,0.0,0.0,0.0,0.571747,0.0
3,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,OpenX,2.0,0.0,0.0,0.005347,0.001716,1.0,1.0,0.0,0.0,0.0,0.858193,0.0
4,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,PubMatic,7.0,0.0,0.0,0.023199,0.007447,2.0,5.0,0.0,0.0,0.0,1.063840,0.0
5,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,Smart RTB+ (Smartadserver),1.0,0.0,0.0,0.001153,0.000370,0.0,0.0,0.0,0.0,0.0,0.370113,0.0
6,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,TripleLift,1.0,0.0,0.0,0.001363,0.000438,0.0,1.0,0.0,0.0,0.0,0.437523,0.0
7,Choose your advertiser name,Desktop_2P_Affinity Categories,0221.com.ar,Smart RTB+ (Smartadserver),8.0,0.0,0.0,0.003680,0.001181,5.0,8.0,0.0,0.0,0.0,0.147660,0.0
8,Choose your advertiser name,Desktop_2P_Affinity Categories,0404.co.il,Google Ad Manager,3.0,0.0,0.0,0.003166,0.001016,3.0,3.0,0.0,0.0,0.0,0.338762,0.0
9,Choose your advertiser name,Desktop_2P_Affinity Categories,0begin.net,Google Ad Manager,1.0,0.0,0.0,0.000637,0.000204,0.0,1.0,0.0,0.0,0.0,0.204477,0.0

In [83]:
## del inventory_data["Unnamed: 0.1"]

In [84]:
inventory_data.head()

,Brand/Company Name,Strategy,App/URL,Exchange,Impressions,Clicks,Total Conversions,Gross Cost,Net Cost,Viewable Impressions,Measurable Impressions,CPC,CTR,CPA,CPM,CVR
0,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,BidSwitch,4.0,0.0,0.0,0.008026,0.002576,1.0,4.0,0.0,0.0,0.0,0.644087,0.0
1,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,Google Ad Manager,1.0,0.0,0.0,0.000592,0.000190,0.0,0.0,0.0,0.0,0.0,0.190032,0.0
2,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,Magnite DV+,7.0,0.0,0.0,0.012468,0.004002,2.0,6.0,0.0,0.0,0.0,0.571747,0.0
3,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,OpenX,2.0,0.0,0.0,0.005347,0.001716,1.0,1.0,0.0,0.0,0.0,0.858193,0.0
4,Choose your advertiser name,Desktop_2P_Affinity Categories,01net.com,PubMatic,7.0,0.0,0.0,0.023199,0.007447,2.0,5.0,0.0,0.0,0.0,1.063840,0.0

In [85]:
# conversions = inventory_data.loc[:,"Total Conversions"]
# impressions = inventory_data.loc[:,"Impressions"]

In [86]:
# conversion_rates = []
# for i in range(len(conversions)):
#     if impressions[i] != 0.0:
#         conversion_rates.append((conversions[i]/impressions[i])*100)
#     else:
#         conversion_rates.append(0.0)

In [87]:
# inventory_data["CVR"] = conversion_rates

In [88]:
# cvr = inventory_data.loc[:,"CVR"] > 0.0
# inventory_data.loc[cvr, :].head(10)

In [89]:
# inventory_data.to_csv("dataset/cleaned_inventory_data.csv", index=False)

In [90]:
inventory_data.nunique()

Brand/Company Name             1
StrategyÂ                      12
App/URL                    50284
Exchange                      25
Impressions                 7863
Clicks                       123
Total Conversions             44
Gross Cost                175596
Net Cost                  175596
Viewable Impressions        5220
Measurable Impressions      7209
CPC                        13040
CTR                         1817
CPA                         6351
CPM                       335400
CVR                         1661
dtype: int64

In [128]:
app_url_imp_mean = inventory_data.loc[:,["App/URL","Impressions"]].groupby("App/URL").mean()
app_url_mean = app_url_imp_mean.sort_values(by="Impressions", ascending=False).head(10)
app_url_mean

                            Impressions
App/URL
mail.yahoo.com            173690.292683
msn.com                   147212.946565
yahoo.com                  88159.987421
weather.com                52698.025157
ebay.com                   49738.801527
zillow.com                 42366.035714
microsoftcasualgames.com   30197.743590
outlook.live.com           29190.898551
taboolanews.com            24268.900000
mail.aol.com               22779.000000

In [129]:
app_url_imp_sum = inventory_data.loc[:,["App/URL","Impressions"]].groupby("App/URL").sum()
app_url_sum = app_url_imp_sum.sort_values(by="Impressions", ascending=False).head(10)
app_url_sum

                   Impressions
App/URL
msn.com             19284896.0
mail.yahoo.com      14242604.0
yahoo.com           14017438.0
weather.com          8378986.0
ebay.com             6515783.0
mail.aol.com         2118447.0
finance.yahoo.com    2117072.0
biblegateway.com     2090330.0
outlook.live.com     2014172.0
realtor.com          1812495.0

## Top 5 App/URL to have Ads display based on impressions

In [131]:
join_app_url_imp = pd.merge(app_url_mean,app_url_sum, on="App/URL", how="inner")
join_app_url_imp.columns = ["impression_mean","impression_sum"]
join_app_url_imp

                  impression_mean  impression_sum
App/URL
mail.yahoo.com      173690.292683      14242604.0
msn.com             147212.946565      19284896.0
yahoo.com            88159.987421      14017438.0
weather.com          52698.025157       8378986.0
ebay.com             49738.801527       6515783.0
outlook.live.com     29190.898551       2014172.0
mail.aol.com         22779.000000       2118447.0

In [132]:
app_url_clicks = inventory_data.loc[:,["App/URL","Clicks"]].groupby("App/URL").mean()
app_url_click_mean = app_url_clicks.sort_values(by="Clicks", ascending=False).head(10)
app_url_click_mean

                     Clicks
App/URL
taboolanews.com   37.300000
mail.yahoo.com    21.170732
mobileposse.com   18.000000
outlook.live.com  13.144928
msn.com            9.572519
cbsnews.com        9.326203
yahoo.com          8.547170
lotterypost.com    7.959459
gosocial.co        6.975904
weather.com        6.459119

In [133]:
app_url_clicks = inventory_data.loc[:,["App/URL","Clicks"]].groupby("App/URL").sum()
app_url_click_sum = app_url_clicks.sort_values(by="Clicks", ascending=False).head(10)
app_url_click_sum

                  Clicks
App/URL
cbsnews.com       1744.0
mail.yahoo.com    1736.0
yahoo.com         1359.0
msn.com           1254.0
the-sun.com       1051.0
weather.com       1027.0
outlook.live.com   907.0
mobileposse.com    864.0
taboolanews.com    746.0
ebay.com           735.0

## Highest App/URL to have Ads display based on clicks

In [134]:
join_app_url_clicks = pd.merge(app_url_click_mean,app_url_click_sum, on="App/URL", how="inner")
join_app_url_clicks.columns = ["click_mean","click_sum"]
join_app_url_clicks

                  click_mean  click_sum
App/URL
taboolanews.com    37.300000      746.0
mail.yahoo.com     21.170732     1736.0
mobileposse.com    18.000000      864.0
outlook.live.com   13.144928      907.0
msn.com             9.572519     1254.0
cbsnews.com         9.326203     1744.0
yahoo.com           8.547170     1359.0
weather.com         6.459119     1027.0

## Highest App/URL to have Ads display based on impressions and clicks

In [136]:
join_impression_click = pd.merge(join_app_url_imp,join_app_url_clicks, on="App/URL", how="inner")
join_impression_click

                  impression_mean  impression_sum  click_mean  click_sum
App/URL
mail.yahoo.com      173690.292683      14242604.0   21.170732     1736.0
msn.com             147212.946565      19284896.0    9.572519     1254.0
yahoo.com            88159.987421      14017438.0    8.547170     1359.0
weather.com          52698.025157       8378986.0    6.459119     1027.0
outlook.live.com     29190.898551       2014172.0   13.144928      907.0

In [74]:
#inven_ori = pd.read_csv("dataset/Inventory.csv", encoding="windows-1254")
impression_count = inventory_data.loc[:,["Exchange","Impressions"]].groupby("Exchange").mean()
impression_count.sort_values(by="Impressions",ascending=False).head(10)

                                 Impressions
Exchange
Taboola                           862.547985
Xandr - Monetize SSP (AppNexus)   466.687318
BidSwitch                         290.553470
Yahoo Exchange                    266.949147
Google Ad Manager                 249.118234
PubMatic                          194.906555
Magnite DV+                       193.821283
Index Exchange                    117.916536
TripleLift                         89.594476
OpenX                              72.485279

In [76]:
click_count = inventory_data.loc[:,["Exchange","Clicks"]].groupby("Exchange").mean()
click_count.sort_values(by="Clicks",ascending=False).head(10)

                                   Clicks
Exchange
Taboola                          0.247421
Google Ad Manager                0.081107
BidSwitch                        0.058275
Xandr - Monetize SSP (AppNexus)  0.054390
PubMatic                         0.046309
Yahoo Exchange                   0.033245
Magnite DV+                      0.031849
Index Exchange                   0.015148
Adform                           0.010490
PulsePoint                       0.010072

In [22]:
conversion_count = inventory_data.loc[:,["Exchange","Total Conversions"]].groupby("Exchange").sum()
conversion_count.sort_values(by="Total Conversions",ascending=False).head(10)

                                 Total Conversions
Exchange
Google Ad Manager                           2323.0
BidSwitch                                    713.0
PubMatic                                     674.0
Magnite DV+                                  431.0
Xandr - Monetize SSP (AppNexus)              369.0
Index Exchange                               271.0
OpenX                                        142.0
Yahoo Exchange                               133.0
TripleLift                                    63.0
Smart RTB+ (Smartadserver)                    49.0

In [77]:
cpc = inventory_data.loc[:,["Exchange","CPC"]].groupby("Exchange").mean()
cpc.sort_values(by="CPC", ascending=False).head(10)

                        CPC
Exchange
Taboola            0.055539
Google Ad Manager  0.022701
BidSwitch          0.022229
Magnite DV+        0.019289
PubMatic           0.014497
Index Exchange     0.009276
Yahoo Exchange     0.008038
TripleLift         0.004938
OpenX              0.004568
PulsePoint         0.004435

In [79]:
cvr = inventory_data.loc[:,["Exchange","CVR"]].groupby("Exchange").mean()
cvr.sort_values(by="CVR", ascending=False).head(10)

                                 CVR
Exchange
GumGum                      0.007456
Kargo                       0.006403
Sharethrough                0.004164
Index Exchange              0.004112
Google Ad Manager           0.003051
Magnite DV+                 0.002587
BidSwitch                   0.002312
OpenX                       0.002183
Smart RTB+ (Smartadserver)  0.002123
Yahoo Exchange              0.002100